language: ruby
rvm:
- 2.5.1
env:
  global:
    - CODECOV_TOKEN: 91f1bbb6-fee9-4f9f-8e72-5d1ebf3e5a2d
    - DEVISE_TOKEN_AUTH_SECRET_KEY="secrets"
services:
  - mongodb
  - elasticsearch
  - redis-server
  - mysql
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client
before_script:
  - cp -f .env.example .env
  - cp -f config/database.travis.yml config/database.yml
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
  - bundle install
script:
  - bundle exec rails db:create RAILS_ENV=test
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rails_best_practices .
  - bundle exec rubocop
  - bin/rspec-testqueue --exclude-pattern "spec/serial_only/**/*_spec.rb" --color --require spec_helper --format progress spec/
  - bundle exec rspec spec/mongo/.
after_failure:
  - mysql -e 'show databases;'
  - cat ./log/test.log
  - echo $RAILS_ENV